#ifndef CHESS_COMMANDS_H
#define CHESS_COMMANDS_H

#define MAX_NUM_COMMAND_ARGS	6

typedef enum
{
	CMD_TYPE_SETTINGS,
	CMD_TYPE_GAME,
} COMMAND_TYPE;

typedef enum
{
	GENERAL_CMD_QUIT = 0,
	/* Settings Commands */ 
	SETTINGS_CMD_SET_GAME_MODE,
	SETTINGS_CMD_SET_DIFFICULTY,  /* Relevant only in Computer AI Mode */
	SETTINGS_CMD_SET_USER_COLOR,  /* Relevant only in Computer AI Mode */
	SETTINGS_CMD_LOAD_BOARD,
	SETTINGS_CMD_CLEAR_BOARD,
	SETTINGS_CMD_SET_NEXT_PLAYER,
	SETTINGS_CMD_REMOVE_PIECE,
	SETTINGS_CMD_SET_PIECE,
	SETTINGS_CMD_PRE_GAME_PRINT_BOARD,   
	SETTINGS_CMD_START_GAME,
	SETTINGS_CMD_MIN = SETTINGS_CMD_SET_GAME_MODE,
	SETTINGS_CMD_MAX = SETTINGS_CMD_START_GAME,
	/* Game Commands */ 
	GAME_CMD_MOVE = SETTINGS_CMD_MAX + 1,
	GAME_CMD_GET_MOVES,
	GAME_CMD_GET_BEST_MOVES,
	GAME_CMD_GET_SCORE,
	GAME_CMD_SAVE,
	CMD_OPCODE_INVALID,
	NUM_OF_COMMANDS,
	GAME_CMD_MIN = GAME_CMD_MOVE,
	GAME_CMD_MAX = GAME_CMD_SAVE,

} CMD_OPCODE;

typedef struct
{
	//COMMAND_TYPE type;
	CMD_OPCODE opcode;
	int argc;   // argv[0] is always the command itself, so argc is always >= 1
	const char* argv[MAX_NUM_COMMAND_ARGS];
} COMMAND;


// todo cancel
typedef enum
{
	CMD_SUCCESS,
	CMD_FAILED,
	CMD_INVALID,
	CMD_INVALID_ARGUMENT,
	CMD_IGNORED,
	NUM_OF_COMMAND_STATUS,

} COMMAND_STATUS;

#endif
