#ifndef CHESS_GUI_LAYOUTS_H
#define CHESS_GUI_LAYOUTS_H

/* LAYOUTS */
#define WINDOW_WIDTH		800
#define WINDOW_HEIGHT		600

/* Notifications */
#define NOTIFICATION_WIDTH			300
#define NOTIFICATION_HEIGHT			120
#define NOTIFICATION_X				50
#define NOTIFICATION_Y				180

/* SETTINGS LAYOUTS */
/* Large Labels */
#define LARGE_LABEL_WIDTH			300
#define LARGE_LABEL_HEIGHT			120
#define MENU_LARGE_LABEL_X			250
#define SETTINGS_WINDOW_Y_SPACER	15
#define SETTINGS_WINDOW_X_SPACER	8
#define SETTINGS_LABEL_HEIGHT_WITH_SPACE  (LARGE_LABEL_HEIGHT + SETTINGS_WINDOW_Y_SPACER)
#define MENU_LARGE_LABEL_0_Y		0
#define MENU_LARGE_LABEL_1_Y		SETTINGS_LABEL_HEIGHT_WITH_SPACE
#define MENU_LARGE_LABEL_2_Y		(SETTINGS_LABEL_HEIGHT_WITH_SPACE << 1)
#define MENU_LARGE_LABEL_3_Y		((SETTINGS_LABEL_HEIGHT_WITH_SPACE << 1) + SETTINGS_LABEL_HEIGHT_WITH_SPACE)

/* Small Labels */
#define SMALL_LABEL_WIDTH			148
#define SMALL_LABEL_HEIGHT			59
#define MENU_SMALL_LABEL_X		   250
#define SETTINGS_SMALL_LABEL_HEIGHT_WITH_SPACE  (SMALL_LABEL_HEIGHT + SETTINGS_WINDOW_Y_SPACER)
#define MENU_SMALL_LABEL_0_Y		MENU_LARGE_LABEL_1_Y + SETTINGS_WINDOW_Y_SPACER
#define MENU_SMALL_LABEL_1_Y		MENU_SMALL_LABEL_0_Y + SETTINGS_SMALL_LABEL_HEIGHT_WITH_SPACE
#define MENU_SMALL_LABEL_2_Y		MENU_SMALL_LABEL_1_Y + SETTINGS_SMALL_LABEL_HEIGHT_WITH_SPACE
#define MENU_SMALL_LABEL_3_Y		MENU_SMALL_LABEL_2_Y + SETTINGS_SMALL_LABEL_HEIGHT_WITH_SPACE
#define MENU_SMALL_LABEL_4_Y		MENU_SMALL_LABEL_3_Y + SETTINGS_SMALL_LABEL_HEIGHT_WITH_SPACE
#define MENU_SMALL_LABEL_5_Y		MENU_SMALL_LABEL_4_Y + SETTINGS_SMALL_LABEL_HEIGHT_WITH_SPACE
#define MENU_SMALL_LABEL_6_Y		MENU_SMALL_LABEL_5_Y + SETTINGS_SMALL_LABEL_HEIGHT_WITH_SPACE

#define MENU_SMALL_LABEL_0_X  MENU_SMALL_LABEL_X
#define MENU_SMALL_LABEL_1_X  (MENU_SMALL_LABEL_0_X + SMALL_LABEL_WIDTH + SETTINGS_WINDOW_X_SPACER)

/* GAME LAYOUTS */
#define GAME_WINDOW_SPACER			16

#define GAME_BACKGROUND_X			0
#define GAME_BACKGROUND_Y			0

#define GUI_PIECE_WIDTH				46
#define GUI_PIECE_HEIGHT			83

#define GAME_BOARD_WIDTH			550
#define GAME_BOARD_HEIGHT			550
#define GAME_BOARD_X				GAME_WINDOW_SPACER
#define GAME_BOARD_Y				GAME_WINDOW_SPACER

#define GAME_MENU_BUTTON_WIDTH		200
#define GAME_MENU_BUTTON_HEIGHT		80

#define GAME_MENU_PANEL_WIDTH		GAME_MENU_BUTTON_WIDTH
#define GAME_MENU_PANEL_HEIGHT		((GAME_MENU_BUTTON_HEIGHT << 2) + (GAME_WINDOW_SPACER + GAME_WINDOW_SPACER + GAME_WINDOW_SPACER))
#define GAME_MENU_PANEL_X			(GAME_WINDOW_SPACER + GAME_BOARD_WIDTH + GAME_WINDOW_SPACER)
#define GAME_MENU_PANEL_Y			GAME_WINDOW_SPACER

#define GAME_MENU_LABELS_X			0
#define GAME_MENU_LABEL_0_Y			0
#define GAME_MENU_LABEL_1_Y			(GAME_MENU_LABEL_0_Y + (GAME_MENU_BUTTON_HEIGHT << 1) + GAME_WINDOW_SPACER)
#define GAME_MENU_LABEL_2_Y			(GAME_MENU_LABEL_1_Y + GAME_MENU_BUTTON_HEIGHT + GAME_WINDOW_SPACER)
#define GAME_MENU_LABEL_3_Y			(GAME_MENU_LABEL_2_Y + GAME_MENU_BUTTON_HEIGHT + GAME_WINDOW_SPACER)


// BOARD SETUP
#define BOARD_SETUP_PIECE_BUTTON_WIDTH	91
#define BOARD_SETUP_PIECE_BUTTON_HEIGHT	58

#define BOARD_SETUP_BUTTON_WIDTH    100
#define BOARD_SETUP_BUTTON_HEIGHT   40
#define BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE  (BOARD_SETUP_PIECE_BUTTON_HEIGHT + 5)
#define BOARD_SETUP_LABEL_0_X			0
#define BOARD_SETUP_LABEL_1_X			(BOARD_SETUP_PIECE_BUTTON_WIDTH + SETTINGS_WINDOW_X_SPACER)
#define BOARD_SETUP_LABEL_MID_X     	(BOARD_SETUP_LABEL_1_X >> 2)

#define BOARD_SETUP_LABEL_0_Y			0
#define BOARD_SETUP_LABEL_1_Y			BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE
#define BOARD_SETUP_LABEL_2_Y			(BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE << 1)
#define BOARD_SETUP_LABEL_3_Y			((BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE << 1) + BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE)
#define BOARD_SETUP_LABEL_4_Y			(BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE << 2)
#define BOARD_SETUP_LABEL_5_Y			((BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE << 2) + BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE)
#define BOARD_SETUP_LABEL_6_Y			((BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE << 2) + (BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE << 1))
#define BOARD_SETUP_LABEL_7_Y			((BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE << 3) - (BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE))
#define BOARD_SETUP_LABEL_8_Y			((BOARD_SETUP_LABEL_HEIGHT_WITH_SPACE << 3))

#define GUI_PIECE_IMAGE_3D_Y_AXIS_ADJUSTMENT		30

/* BOARD LAYOUTS */
//#define GUI_BOARD_POSITION_SIZE		58
#define GUI_BOARD_POSITION_HEIGHT	59
#define GUI_BOARD_POSITION_WIDTH    59
#define GUI_BOARD_POSITION_A_X		42
#define GUI_BOARD_POSITION_B_X		(GUI_BOARD_POSITION_A_X + GUI_BOARD_POSITION_WIDTH)
#define GUI_BOARD_POSITION_C_X		(GUI_BOARD_POSITION_A_X + (GUI_BOARD_POSITION_WIDTH<<1))
#define GUI_BOARD_POSITION_D_X		(GUI_BOARD_POSITION_A_X + (GUI_BOARD_POSITION_WIDTH<<2) - GUI_BOARD_POSITION_WIDTH)
#define GUI_BOARD_POSITION_E_X		(GUI_BOARD_POSITION_A_X + (GUI_BOARD_POSITION_WIDTH<<2))
#define GUI_BOARD_POSITION_F_X		(GUI_BOARD_POSITION_A_X + (GUI_BOARD_POSITION_WIDTH<<2) + GUI_BOARD_POSITION_WIDTH)
#define GUI_BOARD_POSITION_G_X		(GUI_BOARD_POSITION_A_X + (GUI_BOARD_POSITION_WIDTH<<2) + (GUI_BOARD_POSITION_WIDTH<<1))
#define GUI_BOARD_POSITION_H_X		(GUI_BOARD_POSITION_A_X + (GUI_BOARD_POSITION_WIDTH<<3) - GUI_BOARD_POSITION_WIDTH)

#define GUI_BOARD_POSITION_8_Y		43
#define GUI_BOARD_POSITION_7_Y		(GUI_BOARD_POSITION_8_Y + GUI_BOARD_POSITION_HEIGHT)
#define GUI_BOARD_POSITION_6_Y		(GUI_BOARD_POSITION_8_Y + (GUI_BOARD_POSITION_HEIGHT<<1))
#define GUI_BOARD_POSITION_5_Y		(GUI_BOARD_POSITION_8_Y + (GUI_BOARD_POSITION_HEIGHT<<2) - GUI_BOARD_POSITION_HEIGHT)
#define GUI_BOARD_POSITION_4_Y		(GUI_BOARD_POSITION_8_Y + (GUI_BOARD_POSITION_HEIGHT<<2))
#define GUI_BOARD_POSITION_3_Y		(GUI_BOARD_POSITION_8_Y + (GUI_BOARD_POSITION_HEIGHT<<2) + GUI_BOARD_POSITION_HEIGHT)
#define GUI_BOARD_POSITION_2_Y		(GUI_BOARD_POSITION_8_Y + (GUI_BOARD_POSITION_HEIGHT<<2) + (GUI_BOARD_POSITION_HEIGHT<<1))
#define GUI_BOARD_POSITION_1_Y		(GUI_BOARD_POSITION_8_Y + (GUI_BOARD_POSITION_HEIGHT<<3) - GUI_BOARD_POSITION_HEIGHT)

#define PAWN_PROMOTION_PANEL_X			50
#define PAWN_PROMOTION_PANEL_Y			150
#define PAWN_PROMOTION_PANEL_WIDTH		450
#define PAWN_PROMOTION_PANEL_HEIGHT		300
#define PAWN_PROMOTION_BUTTON_0_X		SETTINGS_WINDOW_X_SPACER
#define PAWN_PROMOTION_BUTTON_0_Y		GAME_MENU_BUTTON_HEIGHT + SETTINGS_WINDOW_Y_SPACER
#define PAWN_PROMOTION_BUTTON_1_X		PAWN_PROMOTION_BUTTON_0_X + GAME_MENU_BUTTON_WIDTH + SETTINGS_WINDOW_X_SPACER
#define PAWN_PROMOTION_BUTTON_1_Y		PAWN_PROMOTION_BUTTON_0_Y + GAME_MENU_BUTTON_HEIGHT + SETTINGS_WINDOW_Y_SPACER

#endif