#ifndef INTERFACE_DEFINITIONS_H
#define INTERFACE_DEFINITIONS_H

#define CLI_ARG_STRING_INTERFACE_MODE_CONSOLE   "console"
#define CLI_ARG_STRING_INTERFACE_MODE_GUI       "gui"

#define BOARD_INTERFACE_FIRST_COLUMN            'a'
#define BOARD_INTERFACE_FIRST_ROW               '1'

#endif  // INTERFACE_DEFINITIONS_H